### ISSUE TITLE
Conditional Radios & Checkboxes

### ISSUE THREAD

**Issue by gazjoy** [nhsuk/nhsuk-service-manual-backlog#173]
## What
A conditionally revealing radio and checkbox component. When the radio or checkbox is checked it would reveal some additional content. See GOV.UK example: https://design-system.service.gov.uk/components/radios/conditional-reveal/index.html

## Why
> Explain why you think we should add this to the NHS digital service manual.

I find these components useful for adding a *small amount* of additional information. Contact preferences being a good use case. We'd need to be mindful of advising _when_ to use the component though. I'd imagine it could be open to misuse and the addition of a lot of content and additional interaction.

> - What evidence do you have that services across the NHS need it?

Honestly, none. I am not advocating the inclusion of this component merely adding here so others can feed into it.

> - What evidence do you have that it meets the needs of the users of those services?

None

> - Have you checked that it doesn't already exist in the NHS digital service manual?

Yes, checked with @AdamChrimes via Slack

**Comment by samanthasaw** [comment]
**Submit your electronic declaration service**

Conditional radios and checkboxes are used in the Submit your electronic declaration service. 
Link to prototype: [http://nhs-edec.herokuapp.com/submit-your-edec/index](http://nhs-edec.herokuapp.com/submit-your-edec/index)
Username: user
Password: smartcard

Example of conditional radios: 
[http://nhs-edec.herokuapp.com/submit-your-edec/sections/practice-services/return-user/essential-services-arrangements](http://nhs-edec.herokuapp.com/submit-your-edec/sections/practice-services/return-user/essential-services-arrangements)
![nhs-edec herokuapp com_submit-your-edec_sections_practice-services_return-user_essential-services-arrangements(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/38656667/70526788-46552c80-1b42-11ea-8d2a-6c932a8d4284.png)

Example of conditional checkboxes: 
[http://nhs-edec.herokuapp.com/submit-your-edec/sections/practice-procedures/communicating-with-patients/return-user/call-recall-2](http://nhs-edec.herokuapp.com/submit-your-edec/sections/practice-procedures/communicating-with-patients/return-user/call-recall-2)
![nhs-edec herokuapp com_submit-your-edec_sections_practice-procedures_communicating-with-patients_return-user_call-recall-2(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/38656667/70526841-5d941a00-1b42-11ea-8d7b-778fb1f67f15.png)

**Why I used them:**
I did try to avoid using conditional checkboxes and radios to avoid hiding content from users. 

However using them was a compromise as stakeholders did not want me to add another page where the user would give us that content if they chose 'Other' for example. 

So for example if a user selected Other, what I intended to do was send users to a new page where we would ask them 'What other..' and give them free text to answer. 

**User testing:** 
This prototype was not tested with users.

**Comment by AdamChrimes** [comment]
In a recent project for a new coronavirus service, we required this component. Due to tight deadlines we decided to use another approach but this would have been good to use.

So a +1 for another service requiring it.

**Comment by davidhunter08** [comment]
We used conditional reveals when [asking users for their ethnicity](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/237)

![conditional-reveal-status-checker](https://user-images.githubusercontent.com/14331000/80073005-f1d5ab00-853e-11ea-862f-742ec83c5637.png)

**Note:** this did not go live as a decision was made not to collect this data within this service.

**Comment by SiRose** [comment]
It always feel better on a basic level to expose content rather than to conceal it, but volume and cognitive load matter. Too much of both and users 'lose the feather'. Once a feather wafts away, it's hard to catch it back and can get harder the more you try. Similarly, once people are thrown by not being able to do the next natural thing, it's hard to win them back. Something opening to offer the next step, as a condition of the first step, feels right. All too often users are presented with an 'other' option but no next step to state what the other is. Or, like Sam notes, users get taken somewhere else to expand on that other, changing the flow of where they were and they might not get back to it. Far better, where that next step can be small, to offer it cleanly in situ, to answer it neatly in the existing page narrative. In this sense, a conditionally-revealed checkbox makes ideal sense. Its UX just needs to be tight, in design and content design, to feel natural to the user and not throw them. "You've asked me something, let me tell you."

**Comment by davidhunter08** [comment]
Closing issue as conditional revealing is a variant of the [radios](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/19) and [checkboxes](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/9)
