### ISSUE TITLE
LInks: Wording links that open in a new page

### ISSUE THREAD

**Issue by JackMatthams** [nhsuk/nhsuk-service-manual-backlog#199]
Generally, guidance is to say "opens in a new window" in link text for a link that opens on a new page. 

During work for the new NHS.UK survey banner, two issues were found with this: 

1. "(opens in a new window)" pushed the link in question onto 2 lines on small phones, making it harder to read and use. 

2. Talking about "windows" is outdated, as tabs are more commonly used. 

We believe "(opens new page)" is a better option, as it is short and covers both tab and window browsing.

**Comment by sarawilcox** [comment]
At the January Style Council meeting, we agreed to change the wording in the service manual to:  
"If links do go to a new page, tab or window, warn the user by saying: 'Link name (opens new page)' "

This proposed revision is shorter, meaning it will not push the link over to 2 lines on phones. It also covers both tab and window browsing. We agreed that it would be good to test this with users but were happy with the change for now. 

However, since the meeting, some colleagues in other professions have questioned this and suggested that we keep the standard wording “Opens in a new window”. It’s been suggested that we try to arrange some testing of "page", “tabs” and “windows”. So we've put implementing this as a content style issue on hold.

**Comment by sarawilcox** [comment]
Also at the February Style Council meeting, someone questioned whether we should says "Include all of this in the link text" as we do in the service manual currently. 
![Screenshot 2020-02-25 at 15 49 52](https://user-images.githubusercontent.com/45792959/75263967-9ad58300-57e6-11ea-987a-619a79dcfd70.png)
https://service-manual.nhs.uk/content/links
See also GitHub issues #201 and #182

**Comment by sarawilcox** [comment]
Closing this ticket. I've copied over the contents to the [Links - external](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/182) issue instead.
